AWSTemplateFormatVersion: '2010-09-09'
Description: Static website hosting for Vite React app

Resources:
  ThePrioritizationAppWebsiteBucket:
    Type: AWS::S3::Bucket
    Properties:
      OwnershipControls:
        Rules:
          - ObjectOwnership: BucketOwnerEnforced
      PublicAccessBlockConfiguration:
        BlockPublicAcls: true
        IgnorePublicAcls: true
        BlockPublicPolicy: false
        RestrictPublicBuckets: false
      WebsiteConfiguration:
        IndexDocument: index.html
        ErrorDocument: index.html

  ThePrioritizationAppBucketPolicy:
    Type: AWS::S3::BucketPolicy
    Properties:
      Bucket: !Ref ThePrioritizationAppWebsiteBucket
      PolicyDocument:
        Statement:
          - Effect: Allow
            Principal: '*'
            Action: s3:GetObject
            Resource: !Sub '${ThePrioritizationAppWebsiteBucket.Arn}/*'

  ThePrioritizationAppCloudFrontDistribution:
    Type: AWS::CloudFront::Distribution
    Properties:
      DistributionConfig:
        Enabled: true
        DefaultRootObject: index.html
        Origins:
          - DomainName: !Sub "${ThePrioritizationAppWebsiteBucket}.s3-website-${AWS::Region}.amazonaws.com"
            Id: ThePrioritizationAppS3WebsiteOrigin
            CustomOriginConfig:
              HTTPPort: 80
              HTTPSPort: 443
              OriginProtocolPolicy: http-only
        DefaultCacheBehavior:
          TargetOriginId: ThePrioritizationAppS3WebsiteOrigin
          ViewerProtocolPolicy: redirect-to-https
          CachePolicyId: !Ref ThePrioritizationAppCachePolicy
        CustomErrorResponses:
          - ErrorCode: 403
            ResponseCode: 200
            ResponsePagePath: /index.html
          - ErrorCode: 404
            ResponseCode: 200
            ResponsePagePath: /index.html

  ThePrioritizationAppCachePolicy:
    Type: AWS::CloudFront::CachePolicy
    Properties:
      CachePolicyConfig:
        Name: ThePrioritizationAppNoQueryStringCaching
        DefaultTTL: 3600
        MaxTTL: 86400
        MinTTL: 0
        ParametersInCacheKeyAndForwardedToOrigin:
          QueryStringsConfig:
            QueryStringBehavior: none
          CookiesConfig:
            CookieBehavior: none
          HeadersConfig:
            HeaderBehavior: none
          EnableAcceptEncodingGzip: true
          EnableAcceptEncodingBrotli: true

Outputs:
  ThePrioritizationAppBucketName:
    Value: !Ref ThePrioritizationAppWebsiteBucket
  ThePrioritizationAppCloudFrontURL:
    Value: !GetAtt ThePrioritizationAppCloudFrontDistribution.DomainName
